package com.kodeco.koinmeter.ui.model

data class CoinMarket(
    val id: String,
    val name: String?,
    val symbol: String?,
    val description: String?,
    val image: Image?,
    val marketCapRank: Int?,
    val currentPrice: Double?,
    val ath: Double?,
    val athChangePercentage: Double?,
    val athDate: String?,
    val atl: Double?,
    val atlChangePercentage: Double?,
    val atlDate: String?,
    val marketCap: Double?,
    val marketDataCapRank: Int?,
    val fullyDilutedValuation: Double?,
    val totalVolume: Double?,
    val high24h: Double?,
    val low24h: Double?,
    val priceChange24h: Double?,
    val priceChangePercentage24h: Double?,
    val priceChangePercentage7d: Double?,
    val priceChangePercentage30d: Double?,
    val priceChangePercentage200d: Double?,
    val priceChangePercentage1y: Double?,
    val marketCapChange24h: Double?,
    val marketCapChangePercentage24h: Double?,
    val totalSupply: Double?,
    val maxSupply: Double?,
    val circulatingSupply: Double?,
    val marketLastUpdated: String?,
    val lastUpdated: String?
)
